site_name: "Parag Ekbote"
site_description: "Personal Website "
theme:
  name: "material"
  font:
    text: Open Sans
  features:
    - navigation.footer
    - toc.follow
    - navigation.top
    - navigation.sections
  nav:
  - Home: index.md
  - Education & Work Experience: Education & Work Experience.md
  - Open Source Contributions: Open-Source Contributions.md
  - Projects: Projects.md
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: brown
      accent: light blue

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: teal
      accent: blue
docs_dir: "/workspaces/ParagEkbote.github.io/src"

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

