site_name: "Personal Website🌐"
site_description: "Portfolio Site"
theme:
  name: "material"
  font:
    text: Oxygen Mono
  features:
    - navigation.footer
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: brown
      accent: light blue

    # Light Mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Dark mode
      primary: blue grey
      accent: teal
docs_dir: "/workspaces/ParagEkbote.github.io/src"

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
