name: Weekly OSS Contributions Update

on:
  schedule:
    - cron: '0 12 * * 0'  # Every Sunday at 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update-contributions:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provided by GitHub

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch contributions
        run: python scripts/fetch_contributions.py

      - name: Commit updated file if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add contributions.md
          if ! git diff --cached --quiet; then
            git commit -m "Update contributions.md"
            git push
          else
            echo "No changes to contributions.md, skipping commit."
          fi
